apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-team-fe
  namespace: argocd
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: team-fe
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
